Tracker:AddLocations("locations/A Dark and Stormy Knight 2.json")
Tracker:AddLocations("locations/A Dark and Stormy Knight! 1.json")
Tracker:AddLocations("locations/A Dark and Stormy Knight! 2.json")
Tracker:AddLocations("locations/A Dark and Stormy Knight! 3.json")
Tracker:AddLocations("locations/A One Way Trip to the Crypt 1.json")
Tracker:AddLocations("locations/A One Way Trip to the Crypt 2.json")
Tracker:AddLocations("locations/A One Way Trip to the Crypt 3.json")
Tracker:AddLocations("locations/A One Way Trip to the Crypt 4.json")
Tracker:AddLocations("locations/A Tight Spot for a Grave Plot! 1.json")
Tracker:AddLocations("locations/A Tight Spot for a Grave Plot! 2.json")
Tracker:AddLocations("locations/Aghast by the Mast! 1.json")
Tracker:AddLocations("locations/Aghast by the Mast! 2.json")
Tracker:AddLocations("locations/Aghast by the Mast! 3.json")
Tracker:AddLocations("locations/All Scares Upstairs! 1.json")
Tracker:AddLocations("locations/All Scares Upstairs! 2.json")
Tracker:AddLocations("locations/All Scares Upstairs! 3.json")
Tracker:AddLocations("locations/All Scares Upstairs! 4.json")
Tracker:AddLocations("locations/Chills & Spills on Haunted Hill! 1.json")
Tracker:AddLocations("locations/Chills & Spills on Haunted Hill! 2.json")
Tracker:AddLocations("locations/Chills & Spills on Haunted Hill! 3.json")
Tracker:AddLocations("locations/Clamor in the Manor! 1.json")
Tracker:AddLocations("locations/Clamor in the Manor! 2.json")
Tracker:AddLocations("locations/Clamor in the Manor! 3.json")
Tracker:AddLocations("locations/Clamor in the Manor! 4.json")
Tracker:AddLocations("locations/Coast for some Ghosts! 1.json")
Tracker:AddLocations("locations/Coast for some Ghosts! 2.json")
Tracker:AddLocations("locations/Coast for some Ghosts! 3.json")
Tracker:AddLocations("locations/Cower in the Tower! 1.json")
Tracker:AddLocations("locations/Creepy Crawlies in the Hallways 1.json")
Tracker:AddLocations("locations/Creepy Crawlies in the Hallways 2.json")
Tracker:AddLocations("locations/Creepy Crawlies in the Hallways 3.json")
Tracker:AddLocations("locations/Don't Look Down, Scooby-Doo! 1.json")
Tracker:AddLocations("locations/Don't Look Down, Scooby-Doo! 2.json")
Tracker:AddLocations("locations/Fear on the Pier 1.json")
Tracker:AddLocations("locations/Fear on the Pier 2.json")
Tracker:AddLocations("locations/Fear on the Pier 3.json")
Tracker:AddLocations("locations/Fishy Clues for Scooby-Doo 1.json")
Tracker:AddLocations("locations/Fishy Clues for Scooby-Doo 2.json")
Tracker:AddLocations("locations/Fishy Clues for Scooby-Doo 3.json")
Tracker:AddLocations("locations/Fishy Clues for Scooby-Doo 4.json")
Tracker:AddLocations("locations/Gloom & Doom Down in the Tomb! 1.json")
Tracker:AddLocations("locations/Gloom & Doom Down in the Tomb! 2.json")
Tracker:AddLocations("locations/Gloom & Doom Down in the Tomb! 3.json")
Tracker:AddLocations("locations/Going Down Witch Way 1.json")
Tracker:AddLocations("locations/Gusts Abound Underground 1.json")
Tracker:AddLocations("locations/Gusts Abound Underground 2.json")
Tracker:AddLocations("locations/It's a Mean GreenHouse, Scooby 1.json")
Tracker:AddLocations("locations/It's a Mean GreenHouse, Scooby 2.json")
Tracker:AddLocations("locations/Lighthouse Fright House! 1.json")
Tracker:AddLocations("locations/Lighthouse Fright House! 2.json")
Tracker:AddLocations("locations/Lighthouse Fright House! 3.json")
Tracker:AddLocations("locations/Little Lab of Horrors 1.json")
Tracker:AddLocations("locations/Little Lab of Horrors 2.json")
Tracker:AddLocations("locations/Little Lab of Horrors 3.json")
Tracker:AddLocations("locations/Mastermind Unmasked! 1.json")
Tracker:AddLocations("locations/Mastermind Unmasked! 2.json")
Tracker:AddLocations("locations/Mind Your Manors! 1.json")
Tracker:AddLocations("locations/Mind Your Manors! 2.json")
Tracker:AddLocations("locations/Mind Your Manors! 3.json")
Tracker:AddLocations("locations/Misbehavin' Cause a Cave In 1.json")
Tracker:AddLocations("locations/Misbehavin' Cause a Cave In 2.json")
Tracker:AddLocations("locations/Misbehavin' Cause a Cave In 3.json")
Tracker:AddLocations("locations/Monster Gallery.json")
Tracker:AddLocations("locations/Mystery Machine.json")
Tracker:AddLocations("locations/Mystic Playground.json")
Tracker:AddLocations("locations/On Edge In The Hedge 1.json")
Tracker:AddLocations("locations/On Edge In The Hedge 2.json")
Tracker:AddLocations("locations/On Edge In The Hedge 3.json")
Tracker:AddLocations("locations/On Edge In The Hedge 4.json")
Tracker:AddLocations("locations/On Edge In The Hedge! 4.json")
Tracker:AddLocations("locations/Panic in the Attic! 2.json")
Tracker:AddLocations("locations/Panic in the Attic! 3.json")
Tracker:AddLocations("locations/Panic in the Attic! 4.json")
Tracker:AddLocations("locations/Scared Stiff at Skull Cliff! 1.json")
Tracker:AddLocations("locations/Scared Stiff at Skull Cliff! 2.json")
Tracker:AddLocations("locations/Scared Stiff at Skull Cliff! 3.json")
Tracker:AddLocations("locations/Scared Stiff at Skull Cliff! 4.json")
Tracker:AddLocations("locations/Shiver Your Timbers, Scooby! 1.json")
Tracker:AddLocations("locations/Shiver Your Timbers, Scooby! 2.json")
Tracker:AddLocations("locations/Shock on the Dock 1.json")
Tracker:AddLocations("locations/Shock on the Dock 2.json")
Tracker:AddLocations("locations/Who's Yella' in the Cellar 1.json")
Tracker:AddLocations("locations/Who's Yella' in the Cellar 2.json")
Tracker:AddLocations("locations/Who's Yella' in the Cellar 3.json")
Tracker:AddLocations("locations/Who's Yella' in the Cellar 4.json")
Tracker:AddLocations("locations/Wreck on the Deck! 1.json")
Tracker:AddLocations("locations/Wreck on the Deck! 2.json")
Tracker:AddLocations("locations/Wreck on the Deck! 3.json")
Tracker:AddLocations("locations/Overworld.json")
